# Generated by Django 4.2.7 on 2023-11-30 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_alter_playerround_round_alter_round_tournament_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="round",
            name="name",
            field=models.CharField(
                default="Раунд <django.db.models.fields.IntegerField>", max_length=100
            ),
        ),
    ]
