# Generated by Django 4.2.7 on 2023-12-05 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0004_basket_course_playerscore_delete_playerround_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="course",
            name="par",
        ),
        migrations.AddField(
            model_name="basket",
            name="par",
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="course",
            name="city",
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="course",
            name="country",
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
    ]
