# Generated by Django 4.2.7 on 2023-12-05 00:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0005_remove_course_par_basket_par_course_city_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="course",
            name="baskets_count",
        ),
    ]
