# Generated by Django 4.2.7 on 2023-12-05 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0006_remove_course_baskets_count"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="basket",
            name="course",
        ),
        migrations.CreateModel(
            name="Layout",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="layouts",
                        to="main.course",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="basket",
            name="layout",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="baskets",
                to="main.layout",
            ),
            preserve_default=False,
        ),
    ]
