# Generated by Django 4.2.7 on 2023-12-05 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0008_alter_round_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="round",
            name="name",
            field=models.CharField(
                default="Раунд <django.db.models.fields.IntegerField>", max_length=100
            ),
        ),
    ]
