# Generated by Django 4.2.7 on 2023-12-06 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0011_remove_basket_layout_basket_course_layoutbasket"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tee_number", models.IntegerField()),
                ("par", models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name="basket",
            name="par",
        ),
        migrations.DeleteModel(
            name="LayoutBasket",
        ),
        migrations.AddField(
            model_name="tee",
            name="basket",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="main.basket"
            ),
        ),
        migrations.AddField(
            model_name="tee",
            name="layout",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tees",
                to="main.layout",
            ),
        ),
    ]
