# Generated by Django 4.2.7 on 2023-12-08 22:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0013_rename_tee_segment"),
    ]

    operations = [
        migrations.RenameField(
            model_name="segment",
            old_name="tee_number",
            new_name="segment_number",
        ),
        migrations.RemoveField(
            model_name="playerscore",
            name="basket",
        ),
        migrations.RemoveField(
            model_name="round",
            name="course",
        ),
        migrations.AddField(
            model_name="playerscore",
            name="segment",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="main.segment",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="round",
            name="layout",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="rounds",
                to="main.layout",
            ),
        ),
        migrations.AlterField(
            model_name="segment",
            name="layout",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="segments",
                to="main.layout",
            ),
        ),
    ]
