# Generated by Django 4.2.7 on 2023-12-09 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0014_rename_tee_number_segment_segment_number_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="round",
            name="name",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
